deployments:
- name: flight_local_data
  entrypoint: Orchestrate_file_dataset\orchestrate_FlightPricePrediction.py:main_flow
  work_pool: 
    name: DataTalksClub
- name: flight_s3_data
  entrypoint: Orchestrate_s3\orchestrate_S3_FlightPricePrediction.py:main_flow_s3
  work_pool: 
    name: DataTalksClub