version: '3.7'

volumes:
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "2020:2020"
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - "8989:8080"
    networks:
      - back-tier
      - front-tier

  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana_datasources.yml:/etc/grafana/provisioning/datasources/datasource.yaml.ro
    networks:
      - back-tier
      - front-tier
    restart: always
